const API_BASE="https://atelier-ai-backend-pi.vercel.app";
const PROFILES=[{id:"noelia",name:"Noelia"},{id:"ana-maria",name:"Ana María"},{id:"irene",name:"Irene"}];
const DB_NAME="atelier-armario-db",DB_VERSION=2,STORE="kv";
const appState={profile:null,token:null,data:{garments:[],looks:[]},view:"wardrobe",authExpired:false};
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
function uid(){return crypto.randomUUID?.()||Date.now().toString(36)+Math.random().toString(36).slice(2)}
function esc(v=""){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function toast(msg){const n=$("#toast");n.textContent=msg;n.classList.remove("hidden");clearTimeout(toast.t);toast.t=setTimeout(()=>n.classList.add("hidden"),2400)}
function openDB(){return new Promise((res,rej)=>{const q=indexedDB.open(DB_NAME,DB_VERSION);q.onupgradeneeded=()=>{const d=q.result;if(!d.objectStoreNames.contains(STORE))d.createObjectStore(STORE)};q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)})}
async function dbGet(key){const d=await openDB();return new Promise((res,rej)=>{const q=d.transaction(STORE).objectStore(STORE).get(key);q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)})}
async function dbSet(key,val){const d=await openDB();return new Promise((res,rej)=>{const tx=d.transaction(STORE,"readwrite");tx.objectStore(STORE).put(val,key);tx.oncomplete=()=>res();tx.onerror=()=>rej(tx.error)})}
const stateKey=()=>`state:${appState.profile.id}`;
async function loadState(){appState.data={garments:[],looks:[]};try{const saved=await dbGet(stateKey());if(saved)appState.data={garments:Array.isArray(saved.garments)?saved.garments:[],looks:Array.isArray(saved.looks)?saved.looks:[]}}catch(e){console.error("DB_LOAD",e);toast("No se pudo cargar el armario")}}
async function saveState(){try{await dbSet(stateKey(),appState.data);return true}catch(e){console.error("DB_SAVE",e);toast("No se pudo guardar. Comprueba el espacio disponible.");return false}}
async function api(path,options={}){const headers={...(options.headers||{})};if(appState.token)headers.Authorization=`Bearer ${appState.token}`;const ctrl=new AbortController(),timer=setTimeout(()=>ctrl.abort(),20000);try{const r=await fetch(API_BASE+path,{...options,headers,signal:ctrl.signal});let body={};try{body=await r.json()}catch{}if(r.status===401&&path!=="/api/login"){showAuth();throw new Error("SESSION_EXPIRED")}if(!r.ok)throw new Error(body.error||`HTTP_${r.status}`);return body}finally{clearTimeout(timer)}}
function showAuth(){appState.profile=null;appState.token=null;appState.data={garments:[],looks:[]};appState.view="wardrobe";sessionStorage.removeItem("atelier-session");$("#auth").classList.remove("hidden");$("#app").classList.add("hidden");$("#passwordStep").classList.add("hidden");$("#password").value="";$("#authError").textContent="";$$(".profile-option").forEach(x=>x.classList.remove("selected"))}
function selectProfile(id){appState.profile=PROFILES.find(p=>p.id===id);$$(".profile-option").forEach(x=>x.classList.toggle("selected",x.dataset.profile===id));$("#passwordStep").classList.remove("hidden");$("#password").focus()}
async function login(){if(!appState.profile||$("#loginBtn").disabled)return;const profileId=appState.profile.id,btn=$("#loginBtn"),err=$("#authError");err.textContent="";btn.disabled=true;$(".profile-option").forEach(b=>b.disabled=true);btn.textContent="Entrando…";try{const out=await api("/api/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({profileId,password:$("#password").value})});const token=out.token||out.accessToken;if(!token||out.profileId!==profileId||appState.profile?.id!==profileId)throw new Error("LOGIN_IDENTITY_MISMATCH");appState.token=token;sessionStorage.setItem("atelier-session",JSON.stringify({profile:profileId,token}));await enterApp()}catch(e){console.error("LOGIN",e);err.textContent=e.name==="AbortError"?"La conexión está tardando demasiado.":e.message==="LOGIN_IDENTITY_MISMATCH"?"No se pudo verificar el perfil.":"No se ha podido iniciar sesión. Revisa la contraseña."}finally{btn.disabled=false;$(".profile-option").forEach(b=>b.disabled=false);btn.textContent="Entrar"}}
async function enterApp(){appState.authExpired=false;await loadState();$("#auth").classList.add("hidden");$("#app").classList.remove("hidden");$("#profileName").textContent=appState.profile.name;render()}
async function restoreSession(){try{const s=JSON.parse(sessionStorage.getItem("atelier-session")||"null");if(!s?.profile||!s?.token)return false;const p=PROFILES.find(x=>x.id===s.profile);if(!p)return false;appState.profile=p;appState.token=s.token;const check=await api("/api/session");if(!check.authenticated||check.profileId!==p.id)throw new Error("SESSION_INVALID");await enterApp();return true}catch{sessionStorage.removeItem("atelier-session");appState.profile=null;appState.token=null;return false}}
function setView(view){appState.view=view;$$(".nav-btn").forEach(x=>x.classList.toggle("active",x.dataset.view===view));render()}
function render(){const root=$("#content");if(appState.view==="wardrobe")renderWardrobe(root);else if(appState.view==="looks")renderLooks(root);else renderSettings(root)}
function renderWardrobe(root){const g=appState.data.garments;root.innerHTML=`<section class="hero"><h1>Mi armario</h1><p>Tu colección, organizada a tu manera.</p></section><div class="stats"><div class="stat"><strong>${g.length}</strong><span class="muted">prendas</span></div><div class="stat"><strong>${appState.data.looks.length}</strong><span class="muted">looks</span></div></div><div class="section-head"><h2>Prendas</h2><button class="primary" id="addGarment">+ Añadir</button></div>${g.length?`<div class="grid">${g.map(garmentCard).join("")}</div>`:`<div class="empty"><h3>Tu armario está vacío</h3><p class="muted">Añade tu primera prenda para empezar.</p><button class="primary" id="emptyAdd">Añadir prenda</button></div>`}`;$("#addGarment")?.addEventListener("click",openGarment);$("#emptyAdd")?.addEventListener("click",openGarment);$$("[data-garment]").forEach(x=>x.addEventListener("click",()=>openGarment(x.dataset.garment)))}
function garmentCard(g){const image=typeof g.image==="string"&&/^data:image\/(?:jpeg|png|webp);base64,[a-zA-Z0-9+/=]+$/.test(g.image)?g.image:"";return `<article class="card" data-garment="${esc(g.id)}"><div class="card-img"${image?` style="background-image:url(${image})"`:""}></div><div class="card-body"><div class="card-title">${esc(g.name||"Sin nombre")}</div><div class="card-meta">${esc([g.category,g.color].filter(Boolean).join(" · "))}</div></div></article>`}
function openGarment(id){const g=appState.data.garments.find(x=>x.id===id);$("#garmentTitle").textContent=g?"Editar prenda":"Nueva prenda";$("#garmentId").value=g?.id||"";$("#garmentName").value=g?.name||"";$("#garmentCategory").value=g?.category||"";$("#garmentColor").value=g?.color||"";$("#garmentNotes").value=g?.notes||"";$("#garmentImage").value="";$("#deleteGarment").classList.toggle("hidden",!g);$("#garmentSheet").classList.remove("hidden")}
function closeGarment(){$("#garmentSheet").classList.add("hidden")}
function readImage(file){return new Promise((res,rej)=>{if(!file)return res(null);if(!file.type.startsWith("image/"))return rej(new Error("INVALID_IMAGE"));if(file.size>20*1024*1024)return rej(new Error("IMAGE_TOO_LARGE"));const r=new FileReader();r.onerror=()=>rej(r.error);r.onload=()=>{const img=new Image();img.onerror=()=>rej(new Error("INVALID_IMAGE"));img.onload=()=>{const max=1600,scale=Math.min(1,max/Math.max(img.width,img.height)),w=Math.max(1,Math.round(img.width*scale)),h=Math.max(1,Math.round(img.height*scale)),canvas=document.createElement("canvas");canvas.width=w;canvas.height=h;canvas.getContext("2d").drawImage(img,0,0,w,h);res(canvas.toDataURL("image/jpeg",.82))};img.src=r.result};r.readAsDataURL(file)})}
async function saveGarment(e){e.preventDefault();const id=$("#garmentId").value||uid(),old=appState.data.garments.find(x=>x.id===id),file=$("#garmentImage").files[0];let image=old?.image||"";try{if(file)image=await readImage(file)}catch(e){return toast(e.message==="IMAGE_TOO_LARGE"?"La imagen es demasiado grande":"No se pudo leer la imagen")};const g={id,name:$("#garmentName").value.trim()||"Sin nombre",category:$("#garmentCategory").value,color:$("#garmentColor").value.trim(),notes:$("#garmentNotes").value.trim(),image,updatedAt:new Date().toISOString()};const i=appState.data.garments.findIndex(x=>x.id===id);if(i>=0)appState.data.garments[i]=g;else appState.data.garments.unshift(g);if(!await saveState())return;closeGarment();render();toast("Prenda guardada")}
async function deleteGarment(){const id=$("#garmentId").value;if(!id||!confirm("¿Eliminar esta prenda?"))return;appState.data.garments=appState.data.garments.filter(x=>x.id!==id);appState.data.looks=appState.data.looks.map(l=>({...l,garmentIds:l.garmentIds.filter(x=>x!==id)}));if(!await saveState())return;closeGarment();render();toast("Prenda eliminada")}
async function analyzeGarment(){const file=$("#garmentImage").files[0];if(!file)return toast("Selecciona una foto primero");const btn=$("#analyzeBtn");btn.disabled=true;btn.textContent="Analizando…";try{const image=await readImage(file);const out=await api("/api/analyze",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({image})});const d=out.garment||out.result||out;if(d.name)$("#garmentName").value=d.name;const categoryMap={top:"Arriba",bottom:"Abajo",dress:"Vestidos",outerwear:"Capas",shoes:"Zapatos",bag:"Bolsos",accessory:"Accesorios"};const cat=d.category||categoryMap[d.type];if(cat)$("#garmentCategory").value=cat;if(d.color)$("#garmentColor").value=Array.isArray(d.color)?d.color.join(", "):d.color;toast("Análisis completado")}catch(e){console.error("ANALYZE",e);toast("No se pudo analizar la prenda")}finally{btn.disabled=false;btn.textContent="✨ Analizar foto"}}
function renderLooks(root){const looks=appState.data.looks;root.innerHTML=`<section class="hero"><h1>Looks</h1><p>Combina las prendas que ya tienes.</p></section><div class="section-head"><h2>Mis looks</h2><div><button class="secondary" id="aiLooks">✨ Sugerir</button> <button class="primary" id="newLook">+ Crear</button></div></div>${looks.length?`<div class="grid">${looks.map(lookCard).join("")}</div>`:`<div class="empty"><h3>Aún no tienes looks</h3><p class="muted">Crea uno manualmente con tus prendas.</p><button class="primary" id="emptyLook">Crear look</button></div>`}`;$("#newLook")?.addEventListener("click",openLook);$("#aiLooks")?.addEventListener("click",suggestLooks);$("#emptyLook")?.addEventListener("click",openLook);$$("[data-look]").forEach(x=>x.addEventListener("click",()=>openLook(x.dataset.look)))}
async function suggestLooks(){if(appState.data.garments.length<2)return toast("Añade al menos dos prendas");const btn=$("#aiLooks");btn.disabled=true;btn.textContent="Pensando…";try{const items=appState.data.garments.slice(0,36).map(g=>({i:g.id,n:g.name,c:g.category||"",color:g.color||""}));const out=await api("/api/looks",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({items,need:3,occasion:"libre",season:"cualquiera"})});const suggestions=Array.isArray(out.looks)?out.looks:[];if(!suggestions.length)return toast("No se encontraron combinaciones");for(const [i,l] of suggestions.entries())appState.data.looks.unshift({id:uid(),name:l.why||`Look sugerido ${i+1}`,garmentIds:l.ids,ai:true,updatedAt:new Date().toISOString()});if(!await saveState())return;render();toast(`${suggestions.length} looks sugeridos`)}catch(e){console.error("LOOKS_AI",e);toast("No se pudieron generar looks")}finally{if($("#aiLooks")){$("#aiLooks").disabled=false;$("#aiLooks").textContent="✨ Sugerir"}}}
function lookCard(l){const names=l.garmentIds.map(id=>appState.data.garments.find(g=>g.id===id)?.name).filter(Boolean);return `<article class="card" data-look="${esc(l.id)}"><div class="card-body"><div class="card-title">${esc(l.name)}</div><div class="look-items">${names.map(n=>`<span class="look-chip">${esc(n)}</span>`).join("")}</div></div></article>`}
function openLook(id){const l=appState.data.looks.find(x=>x.id===id);$("#lookTitle").textContent=l?"Editar look":"Nuevo look";$("#lookId").value=l?.id||"";$("#lookName").value=l?.name||"";$("#lookGarments").innerHTML=appState.data.garments.length?appState.data.garments.map(g=>`<label class="field"><span><input type="checkbox" value="${esc(g.id)}" ${l?.garmentIds.includes(g.id)?"checked":""}> ${esc(g.name)}</span></label>`).join(""):`<p class="muted">Añade prendas antes de crear un look.</p>`;$("#deleteLook").classList.toggle("hidden",!l);$("#lookSheet").classList.remove("hidden")}
function closeLook(){$("#lookSheet").classList.add("hidden")}
async function saveLook(e){e.preventDefault();const id=$("#lookId").value||uid(),garmentIds=$$("#lookGarments input:checked").map(x=>x.value);if(!garmentIds.length)return toast("Selecciona al menos una prenda");const l={id,name:$("#lookName").value.trim()||"Mi look",garmentIds,updatedAt:new Date().toISOString()};const i=appState.data.looks.findIndex(x=>x.id===id);if(i>=0)appState.data.looks[i]=l;else appState.data.looks.unshift(l);if(!await saveState())return;closeLook();render();toast("Look guardado")}
async function deleteLook(){const id=$("#lookId").value;if(!id||!confirm("¿Eliminar este look?"))return;appState.data.looks=appState.data.looks.filter(x=>x.id!==id);if(!await saveState())return;closeLook();render();toast("Look eliminado")}
function renderSettings(root){root.innerHTML=`<section class="hero"><h1>Ajustes</h1><p>Sesión de ${esc(appState.profile.name)}.</p></section><div class="section-head"><h2>Cuenta</h2></div><div class="card"><div class="card-body"><p>Los datos del armario se guardan localmente en este dispositivo y separados por perfil.</p><button class="danger" id="logout">Cerrar sesión</button></div></div>`;$("#logout").addEventListener("click",showAuth)}
function bind(){$$(".profile-option").forEach(b=>b.addEventListener("click",()=>selectProfile(b.dataset.profile)));$("#loginBtn").addEventListener("click",login);$("#password").addEventListener("keydown",e=>{if(e.key==="Enter")login()});$$(".nav-btn").forEach(b=>b.addEventListener("click",()=>setView(b.dataset.view)));$("#garmentForm").addEventListener("submit",saveGarment);$("#closeGarment").addEventListener("click",closeGarment);$("#deleteGarment").addEventListener("click",deleteGarment);$("#analyzeBtn").addEventListener("click",analyzeGarment);$("#lookForm").addEventListener("submit",saveLook);$("#closeLook").addEventListener("click",closeLook);$("#deleteLook").addEventListener("click",deleteLook);$("#profileName").addEventListener("click",()=>setView("settings"))}
document.addEventListener("DOMContentLoaded",async()=>{bind();if(!await restoreSession())showAuth();if("serviceWorker" in navigator){navigator.serviceWorker.register("./sw.js").catch(e=>console.warn("SW",e))}});