const API_BASE="https://atelier-ai-backend-pi.vercel.app";
const PROFILES=[{id:"noelia",name:"Noelia"},{id:"ana-maria",name:"Ana María"},{id:"irene",name:"Irene"}];
const DB_NAME="atelier-armario-db",DB_VERSION=2,STORE="kv";
const emptyData=()=>({garments:[],looks:[],wishlist:[],wearLog:[],feedback:{},preferences:{forgottenDays:60,diversity:65,occasion:"daily",season:"all",budget:100,avoidRepeats:true}});
function normalizeData(v){const d=emptyData();if(!v||typeof v!=="object")return d;for(const key of ["garments","looks","wishlist","wearLog"])if(Array.isArray(v[key]))d[key]=v[key];if(v.feedback&&typeof v.feedback==="object"&&!Array.isArray(v.feedback))d.feedback=v.feedback;if(v.preferences&&typeof v.preferences==="object")d.preferences={...d.preferences,...v.preferences};return d}
const copyData=d=>structuredClone(d);
const appState={profile:null,token:null,data:emptyData(),view:"wardrobe",authExpired:false};let lastSavedData=emptyData();
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
function uid(){return crypto.randomUUID?.()||Date.now().toString(36)+Math.random().toString(36).slice(2)}
function esc(v=""){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function toast(msg){const n=$("#toast");n.textContent=msg;n.classList.remove("hidden");clearTimeout(toast.t);toast.t=setTimeout(()=>n.classList.add("hidden"),2400)}
let dbPromise=null;function openDB(){if(dbPromise)return dbPromise;dbPromise=new Promise((res,rej)=>{const q=indexedDB.open(DB_NAME,DB_VERSION);q.onupgradeneeded=()=>{const d=q.result;if(!d.objectStoreNames.contains(STORE))d.createObjectStore(STORE)};q.onsuccess=()=>{const db=q.result;db.onversionchange=()=>{db.close();dbPromise=null};res(db)};q.onerror=()=>rej(q.error);q.onblocked=()=>rej(new Error("DB_BLOCKED"))}).catch(e=>{dbPromise=null;throw e});return dbPromise}
async function dbGet(key){const d=await openDB();return new Promise((res,rej)=>{const q=d.transaction(STORE).objectStore(STORE).get(key);q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)})}
async function dbSet(key,val){const d=await openDB();return new Promise((res,rej)=>{const tx=d.transaction(STORE,"readwrite");tx.objectStore(STORE).put(val,key);tx.oncomplete=()=>res();tx.onerror=()=>rej(tx.error)})}
const stateKey=()=>`state:${appState.profile.id}`;
async function loadState(){appState.data=emptyData();try{const saved=await dbGet(stateKey());appState.data=normalizeData(saved)}catch(e){console.error("DB_LOAD",e);toast("No se pudo cargar el armario")}finally{lastSavedData=copyData(appState.data)}}
async function saveState(){try{await dbSet(stateKey(),appState.data);lastSavedData=copyData(appState.data);return true}catch(e){console.error("DB_SAVE",e);appState.data=copyData(lastSavedData);if(appState.profile)render();toast("No se pudo guardar. Comprueba el espacio disponible.");return false}}
async function api(path,options={}){const headers={...(options.headers||{})};if(appState.token)headers.Authorization=`Bearer ${appState.token}`;const ctrl=new AbortController(),timer=setTimeout(()=>ctrl.abort(),20000);try{const r=await fetch(API_BASE+path,{...options,headers,signal:ctrl.signal});let body={};try{body=await r.json()}catch{}if(r.status===401&&path!=="/api/login"){showAuth();throw new Error("SESSION_EXPIRED")}if(!r.ok)throw new Error(body.error||`HTTP_${r.status}`);return body}finally{clearTimeout(timer)}}
function showAuth(){appState.profile=null;appState.token=null;appState.data=emptyData();lastSavedData=emptyData();appState.view="wardrobe";$("#content").replaceChildren();$("#profileName").textContent="";$("#garmentForm").reset();$("#lookForm").reset();$("#lookGarments").replaceChildren();$("#garmentSheet").classList.add("hidden");$("#lookSheet").classList.add("hidden");try{localStorage.removeItem("atelier-session")}catch{};$("#auth").classList.remove("hidden");$("#app").classList.add("hidden");$("#passwordStep").classList.add("hidden");$("#password").value="";$("#authError").textContent="";$$(".profile-option").forEach(x=>x.classList.remove("selected"))}
function selectProfile(id){appState.profile=PROFILES.find(p=>p.id===id);$$(".profile-option").forEach(x=>x.classList.toggle("selected",x.dataset.profile===id));$("#passwordStep").classList.remove("hidden");$("#password").focus()}
async function login(){if(!appState.profile||$("#loginBtn").disabled)return;const profileId=appState.profile.id,btn=$("#loginBtn"),err=$("#authError");err.textContent="";btn.disabled=true;$$(".profile-option").forEach(b=>b.disabled=true);btn.textContent="Entrando…";try{const out=await api("/api/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({profileId,password:$("#password").value})});const token=out.token||out.accessToken;if(!token||out.profileId!==profileId||appState.profile?.id!==profileId)throw new Error("LOGIN_IDENTITY_MISMATCH");appState.token=token;localStorage.setItem("atelier-session",JSON.stringify({profile:profileId,token}));await enterApp()}catch(e){console.error("LOGIN",e);err.textContent=e.name==="AbortError"?"La conexión está tardando demasiado.":e.message==="LOGIN_IDENTITY_MISMATCH"?"No se pudo verificar el perfil.":"No se ha podido iniciar sesión. Revisa la contraseña."}finally{btn.disabled=false;$$(".profile-option").forEach(b=>b.disabled=false);btn.textContent="Entrar"}}
async function enterApp(){appState.authExpired=false;await loadState();$("#auth").classList.add("hidden");$("#app").classList.remove("hidden");$("#profileName").textContent=appState.profile.name;render()}
async function restoreSession(){try{sessionStorage.removeItem("atelier-session")}catch{}let s=null;try{s=JSON.parse(localStorage.getItem("atelier-session")||"null")}catch{}try{if(!s?.profile||!s?.token)return false;const p=PROFILES.find(x=>x.id===s.profile);if(!p)return false;appState.profile=p;appState.token=s.token;const check=await api("/api/session");if(!check.authenticated||check.profileId!==p.id)throw new Error("SESSION_INVALID");await enterApp();return true}catch(e){if(appState.token&&appState.profile&&e.message!=="SESSION_INVALID"&&e.message!=="SESSION_EXPIRED"){try{await enterApp();return true}catch{}}try{localStorage.removeItem("atelier-session")}catch{}appState.profile=null;appState.token=null;return false}}
function setView(view){appState.view=view;$$(".nav-btn").forEach(x=>x.classList.toggle("active",x.dataset.view===view));render()}
function render(){const root=$("#content");if(appState.view==="wardrobe")renderWardrobe(root);else if(appState.view==="looks")renderLooks(root);else renderSettings(root)}
function renderWardrobe(root){const g=appState.data.garments;root.innerHTML=`<section class="hero"><h1>Mi armario</h1><p>Tu colección, organizada a tu manera.</p></section><div class="stats"><div class="stat"><strong>${g.length}</strong><span class="muted">prendas</span></div><div class="stat"><strong>${appState.data.looks.length}</strong><span class="muted">looks</span></div></div><div class="section-head"><h2>Prendas</h2><button class="primary" id="addGarment">+ Añadir</button></div>${g.length?`<div class="grid">${g.map(garmentCard).join("")}</div>`:`<div class="empty"><h3>Tu armario está vacío</h3><p class="muted">Añade tu primera prenda para empezar.</p><button class="primary" id="emptyAdd">Añadir prenda</button></div>`}`;$("#addGarment")?.addEventListener("click",openGarment);$("#emptyAdd")?.addEventListener("click",openGarment);$$("[data-garment]").forEach(x=>x.addEventListener("click",()=>openGarment(x.dataset.garment)))}
function garmentCard(g){const image=typeof g.image==="string"&&/^data:image\/(?:jpeg|png|webp);base64,[a-zA-Z0-9+/=]+$/.test(g.image)?g.image:"";return `<article class="card" data-garment="${esc(g.id)}"><div class="card-img"${image?` style="background-image:url(${image})"`:""}></div><div class="card-body"><div class="card-title">${esc(g.name||"Sin nombre")}</div><div class="card-meta">${esc([g.category,g.color].filter(Boolean).join(" · "))}</div></div></article>`}
function openGarment(id){const g=appState.data.garments.find(x=>x.id===id);$("#garmentTitle").textContent=g?"Editar prenda":"Nueva prenda";$("#garmentId").value=g?.id||"";$("#garmentName").value=g?.name||"";$("#garmentCategory").value=g?.category||"";$("#garmentColor").value=g?.color||"";$("#garmentNotes").value=g?.notes||"";$("#garmentSeason").value=g?.season||"all";$("#garmentStyle").value=g?.style||"";$("#garmentPrice").value=g?.price??"";$("#garmentBought").value=g?.boughtAt||"";$("#garmentFavorite").checked=!!g?.favorite;$("#garmentImage").value="";const preview=$("#garmentPreview");const valid=typeof g?.image==="string"&&/^data:image\/(?:jpeg|png|webp);base64,/.test(g.image);preview.src=valid?g.image:"";preview.classList.toggle("hidden",!valid);$("#deleteGarment").classList.toggle("hidden",!g);lastAnalysis=null;$("#garmentSheet").classList.remove("hidden")}
const ANALYSIS_FIELDS={pattern:["plain","stripes","checks","floral","animal","dots","graphic","other"],fabric:["unknown","cotton","denim","linen","wool","knit","leather","satin","silk","synthetic","mixed"],length:["na","cropped","regular","midi","long"],formality:["casual","smartcasual","formal","party","sport"]};let lastAnalysis=null;
function cleanAnalysis(d){const o={};for(const [k,list] of Object.entries(ANALYSIS_FIELDS))if(list.includes(d?.[k]))o[k]=d[k];if(Array.isArray(d?.occasions)){const occ=d.occasions.filter(x=>["daily","work","dinner","event","travel"].includes(x));if(occ.length)o.occasions=[...new Set(occ)]}return o}
function closeGarment(){$("#garmentSheet").classList.add("hidden")}
function readImage(file){return new Promise((res,rej)=>{if(!file)return res(null);if(!file.type.startsWith("image/"))return rej(new Error("INVALID_IMAGE"));if(file.size>20*1024*1024)return rej(new Error("IMAGE_TOO_LARGE"));const r=new FileReader();r.onerror=()=>rej(r.error);r.onload=()=>{const img=new Image();img.onerror=()=>rej(new Error("INVALID_IMAGE"));img.onload=()=>{const max=1600,scale=Math.min(1,max/Math.max(img.width,img.height)),w=Math.max(1,Math.round(img.width*scale)),h=Math.max(1,Math.round(img.height*scale)),canvas=document.createElement("canvas");canvas.width=w;canvas.height=h;canvas.getContext("2d").drawImage(img,0,0,w,h);res(canvas.toDataURL("image/jpeg",.82))};img.src=r.result};r.readAsDataURL(file)})}
async function saveGarment(e){e.preventDefault();const id=$("#garmentId").value||uid(),old=appState.data.garments.find(x=>x.id===id),file=$("#garmentImage").files[0];let image=old?.image||"";try{if(file)image=await readImage(file)}catch(e){return toast(e.message==="IMAGE_TOO_LARGE"?"La imagen es demasiado grande":"No se pudo leer la imagen")};if(!image)return toast("Añade una fotografía de la prenda antes de guardarla");const g={...Object.fromEntries(Object.keys(ANALYSIS_FIELDS).concat("occasions").map(k=>[k,old?.[k]]).filter(x=>x[1]!==undefined)),...(lastAnalysis||{}),id,name:$("#garmentName").value.trim()||"Sin nombre",category:$("#garmentCategory").value,color:$("#garmentColor").value.trim(),notes:$("#garmentNotes").value.trim(),season:$("#garmentSeason").value,style:$("#garmentStyle").value,price:$("#garmentPrice").value===""?null:Number($("#garmentPrice").value),boughtAt:$("#garmentBought").value,favorite:$("#garmentFavorite").checked,createdAt:old?.createdAt||new Date().toISOString(),image,updatedAt:new Date().toISOString()};const i=appState.data.garments.findIndex(x=>x.id===id);if(i>=0)appState.data.garments[i]=g;else appState.data.garments.unshift(g);if(!await saveState())return;closeGarment();render();toast("Prenda guardada")}
async function deleteGarment(){const id=$("#garmentId").value;if(!id||!confirm("¿Eliminar esta prenda?"))return;appState.data.garments=appState.data.garments.filter(x=>x.id!==id);appState.data.looks=appState.data.looks.map(l=>({...l,garmentIds:l.garmentIds.filter(x=>x!==id)}));if(!await saveState())return;closeGarment();render();toast("Prenda eliminada")}
async function analyzeGarment(){const file=$("#garmentImage").files[0];if(!file)return toast("Selecciona una foto primero");const btn=$("#analyzeBtn");btn.disabled=true;btn.textContent="Analizando…";try{const image=await readImage(file);const out=await api("/api/analyze",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({image})});const d=out.garment||out.result||out;lastAnalysis=cleanAnalysis(d);if(d.name)$("#garmentName").value=d.name;const categoryMap={top:"Arriba",bottom:"Abajo",dress:"Vestidos",outerwear:"Capas",shoes:"Zapatos",bag:"Bolsos",accessory:"Accesorios"};const cat=categoryMap[d.category]||d.category||categoryMap[d.type];if(cat)$("#garmentCategory").value=cat;if(d.color)$("#garmentColor").value=Array.isArray(d.color)?d.color.join(", "):d.color;if(d.style){const style=d.style==="basic"?"casual":d.style;if(["casual","smart","party","sport"].includes(style))$("#garmentStyle").value=style}if(["all","warm","cold"].includes(d.season))$("#garmentSeason").value=d.season;if(d.notes&&!$("#garmentNotes").value.trim())$("#garmentNotes").value=String(d.notes).slice(0,500);toast("Análisis completado")}catch(e){console.error("ANALYZE",e);toast("No se pudo analizar la prenda")}finally{btn.disabled=false;btn.textContent="✨ Analizar foto"}}
function renderLooks(root){const looks=appState.data.looks;root.innerHTML=`<section class="hero"><h1>Looks</h1><p>Combina las prendas que ya tienes.</p></section><div class="section-head"><h2>Mis looks</h2><div><button class="secondary" id="aiLooks">✨ Sugerir</button> <button class="primary" id="newLook">+ Crear</button></div></div>${looks.length?`<div class="grid">${looks.map(lookCard).join("")}</div>`:`<div class="empty"><h3>Aún no tienes looks</h3><p class="muted">Crea uno manualmente con tus prendas.</p><button class="primary" id="emptyLook">Crear look</button></div>`}`;$("#newLook")?.addEventListener("click",openLook);$("#aiLooks")?.addEventListener("click",suggestLooks);$("#emptyLook")?.addEventListener("click",openLook);$$("[data-look]").forEach(x=>x.addEventListener("click",()=>openLook(x.dataset.look)))}
const aiLookCache=new Map();
async function suggestLooks(){
 if(appState.data.garments.length<2)return toast("Añade al menos dos prendas");
 const btn=$("#aiLooks")||$("#suggestSmart");if(!btn||btn.disabled)return;btn.disabled=true;btn.textContent="Pensando…";
 try{
  const p=appState.data.preferences||{},sorted=typeof recommendGarments==="function"?recommendGarments():appState.data.garments;
  const items=sorted.slice(0,36).map(g=>({i:g.id,n:g.name,c:g.category||"",color:g.color||"",style:g.style||"",pattern:g.pattern||"",formality:g.formality||"",used:typeof wornCount==="function"?wornCount(g.id):0,forgotten:typeof forgottenStatus==="function"?forgottenStatus(g).forgotten:false}));
  const recent=(appState.data.wearLog||[]).slice(0,8).flatMap(l=>l.garmentIds||[]);
  const avoid=p.avoidRepeats?[...new Set(recent)].slice(0,12):[];
  const fb=appState.data.feedback||{},taste=v=>appState.data.looks.filter(l=>fb[l.id]===v&&Array.isArray(l.garmentIds)&&l.garmentIds.length>1).slice(0,6).map(l=>l.garmentIds.slice(0,6));
  const body={items,need:3,liked:taste("up"),disliked:taste("down"),occasion:p.occasion||"daily",season:p.season||"all",weather:p.temperature==null||p.temperature===""?"25 °C":String(p.temperature)+" °C",diversity:p.diversity??65,avoid};
  const key=appState.profile.id+":"+JSON.stringify(body);const cached=aiLookCache.get(key);
  const out=cached&&Date.now()-cached.at<300000?cached.value:await api("/api/looks",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});
  if(!cached||Date.now()-cached.at>=300000)aiLookCache.set(key,{at:Date.now(),value:out});
  const suggestions=Array.isArray(out.looks)?out.looks:[],allowed=new Set(items.map(i=>i.i));
  const seen=new Set(appState.data.looks.map(l=>(l.garmentIds||[]).slice().sort().join("|")));let added=0;
  for(const [i,l] of suggestions.entries()){
   const ids=[...new Set(Array.isArray(l.ids)?l.ids:[])].filter(id=>allowed.has(id)).slice(0,6),signature=ids.slice().sort().join("|");
   if(ids.length<2||seen.has(signature))continue;
   seen.add(signature);added++;appState.data.looks.unshift({id:uid(),name:String(l.why||"Look sugerido "+(i+1)).slice(0,80),garmentIds:ids,ai:true,occasion:body.occasion,updatedAt:new Date().toISOString()});
  }
  if(!added)return toast("Estas combinaciones ya están guardadas. Cambia la ocasión o la diversidad.");
  if(!await saveState())return;render();toast(added+" looks sugeridos");
 }catch(e){console.error("LOOKS_AI",e);toast(e.message==="SESSION_EXPIRED"?"La sesión ha caducado":"No se pudieron generar looks")}
 finally{if($("#aiLooks")){$("#aiLooks").disabled=false;$("#aiLooks").textContent="✦ Sugerir"}if($("#suggestSmart")){$("#suggestSmart").disabled=false;$("#suggestSmart").textContent="✦ Generar looks con mi ropa"}}
}
function lookCard(l){const names=l.garmentIds.map(id=>appState.data.garments.find(g=>g.id===id)?.name).filter(Boolean);return `<article class="card" data-look="${esc(l.id)}"><div class="card-body"><div class="card-title">${esc(l.name)}</div><div class="look-items">${names.map(n=>`<span class="look-chip">${esc(n)}</span>`).join("")}</div></div></article>`}
function openLook(id){const l=appState.data.looks.find(x=>x.id===id);$("#lookTitle").textContent=l?"Editar look":"Nuevo look";$("#lookId").value=l?.id||"";$("#lookName").value=l?.name||"";$("#lookOccasion").value=l?.occasion||"daily";$("#lookFavorite").checked=!!l?.favorite;$("#lookGarments").innerHTML=appState.data.garments.length?appState.data.garments.map(g=>`<label class="field"><span><input type="checkbox" value="${esc(g.id)}" ${l?.garmentIds.includes(g.id)?"checked":""}> ${esc(g.name)}</span></label>`).join(""):`<p class="muted">Añade prendas antes de crear un look.</p>`;$("#deleteLook").classList.toggle("hidden",!l);$("#lookSheet").classList.remove("hidden")}
function closeLook(){$("#lookSheet").classList.add("hidden")}
async function saveLook(e){e.preventDefault();const id=$("#lookId").value||uid(),garmentIds=$$("#lookGarments input:checked").map(x=>x.value);if(!garmentIds.length)return toast("Selecciona al menos una prenda");const previous=appState.data.looks.find(x=>x.id===id);const l={id,name:$("#lookName").value.trim()||"Mi look",garmentIds,occasion:$("#lookOccasion").value,favorite:$("#lookFavorite").checked,ai:previous?.ai||false,updatedAt:new Date().toISOString()};const i=appState.data.looks.findIndex(x=>x.id===id);if(i>=0)appState.data.looks[i]=l;else appState.data.looks.unshift(l);if(!await saveState())return;closeLook();render();toast("Look guardado")}
async function deleteLook(){const id=$("#lookId").value;if(!id||!confirm("¿Eliminar este look?"))return;appState.data.looks=appState.data.looks.filter(x=>x.id!==id);if(!await saveState())return;closeLook();render();toast("Look eliminado")}
function renderSettings(root){root.innerHTML=`<section class="hero"><h1>Ajustes</h1><p>Sesión de ${esc(appState.profile.name)}.</p></section><div class="section-head"><h2>Cuenta</h2></div><div class="card"><div class="card-body"><p>Los datos del armario se guardan localmente en este dispositivo y separados por perfil.</p><button class="danger" id="logout">Cerrar sesión</button></div></div>`;$("#logout").addEventListener("click",showAuth)}
function bind(){$$(".profile-option").forEach(b=>b.addEventListener("click",()=>selectProfile(b.dataset.profile)));$("#loginBtn").addEventListener("click",login);$("#password").addEventListener("keydown",e=>{if(e.key==="Enter")login()});$$(".nav-btn").forEach(b=>b.addEventListener("click",()=>setView(b.dataset.view)));$("#garmentForm").addEventListener("submit",saveGarment);$("#closeGarment").addEventListener("click",closeGarment);$("#deleteGarment").addEventListener("click",deleteGarment);$("#analyzeBtn").addEventListener("click",analyzeGarment);$("#garmentImage").addEventListener("change",async e=>{const f=e.target.files[0],p=$("#garmentPreview");if(!f){p.src="";p.classList.add("hidden");return}try{p.src=await readImage(f);p.classList.remove("hidden")}catch(err){p.src="";p.classList.add("hidden");toast("No se pudo previsualizar la imagen")}});$("#lookForm").addEventListener("submit",saveLook);$("#closeLook").addEventListener("click",closeLook);$("#deleteLook").addEventListener("click",deleteLook);$("#profileName").addEventListener("click",()=>setView("settings"))}
document.addEventListener("DOMContentLoaded",async()=>{bind();if(!await restoreSession())showAuth();if("serviceWorker" in navigator){navigator.serviceWorker.register("./sw.js").catch(e=>console.warn("SW",e))}});