import { chromium, devices } from "playwright";
import assert from "node:assert/strict";
const browser=await chromium.launch({headless:true,channel:"chrome"});
const context=await browser.newContext({...devices["iPhone 13"],browserName:undefined});
const page=await context.newPage();
const errors=[];
let forceUnauthorized=false,forceServerError=false;
page.on("pageerror",e=>errors.push(e.message));
page.on("console",m=>{if(m.type()==="error")console.log("BROWSER_CONSOLE",m.text())});
page.on("requestfailed",r=>console.log("FAILED_REQUEST",r.url(),r.failure()?.errorText));
await page.route("https://atelier-ai-backend-pi.vercel.app/**",async route=>{
 const req=route.request(),url=req.url(),origin="http://127.0.0.1:8000";
 const headers={"access-control-allow-origin":origin,"access-control-allow-headers":"Content-Type, Authorization","access-control-allow-methods":"GET, POST, OPTIONS","content-type":"application/json"};
 console.log("MOCK",req.method(),url);if(req.method()==="OPTIONS")return route.fulfill({status:204,headers,body:""});
 if(url.endsWith("/api/login")){const body=JSON.parse(req.postData()||"{}");return route.fulfill({status:200,headers,body:JSON.stringify({profileId:body.profileId,token:"test-token"})})}
 if(url.endsWith("/api/session"))return route.fulfill({status:200,headers,body:JSON.stringify({authenticated:true,profileId:currentProfile})});
 if(url.endsWith("/api/analyze"))return route.fulfill({status:200,headers,body:JSON.stringify({garment:{name:"Camisa reconocida por IA",type:"top",color:"Azul",fabric:"cotton",pattern:"stripes",fit:"regular",sleeve:"larga",subtype:"camisa",confidence:"media",details:"botones frontales",occasions:["daily","work"]}})});
 if(url.endsWith("/api/looks")&&forceUnauthorized){forceUnauthorized=false;return route.fulfill({status:401,headers,body:JSON.stringify({error:"Sesión caducada"})})}
 if(url.endsWith("/api/looks")&&forceServerError){forceServerError=false;return route.fulfill({status:503,headers,body:JSON.stringify({error:"Servicio no disponible"})})}
 if(url.endsWith("/api/looks")){const items=JSON.parse(req.postData()||"{}").items||[];return route.fulfill({status:200,headers,body:JSON.stringify({looks:[{ids:items.slice(0,2).map(x=>x.i),why:"Look de prueba IA"}]})})}
 return route.fulfill({status:500,headers,body:JSON.stringify({error:"Mock AI unavailable"})});
});
let currentProfile="noelia";
try{
 await page.goto("http://127.0.0.1:8000/atelier/",{waitUntil:"networkidle"});
 await page.getByRole("button",{name:"Noelia"}).click();
 await page.locator("#password").fill("test");
 await page.locator("#loginBtn").click();
 await page.getByRole("heading",{name:"Mi armario"}).waitFor({timeout:6000}).catch(async e=>{console.log("LOGIN_DIAGNOSTIC",{error:await page.locator("#authError").textContent(),authVisible:await page.locator("#auth").isVisible(),appVisible:await page.locator("#app").isVisible(),browserErrors:errors});throw e});
 assert.equal(await page.locator("#app").isVisible(),true);
 assert.equal(await page.locator("#auth").isVisible(),false);
 const bg=await page.locator("body").evaluate(el=>getComputedStyle(el).backgroundColor);
 assert.notEqual(bg,"rgba(0, 0, 0, 0)","CSS not applied");
 await page.locator("#addGarment").click();
 await page.locator("#autoAnalyze").uncheck();
 await page.locator("#garmentName").fill("Prenda auditada");
 await page.locator("#garmentCategory").selectOption("Arriba");
 const tinyPng=Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/pVYAAAAASUVORK5CYII=","base64");
 await page.locator("#garmentImage").setInputFiles({name:"foto.png",mimeType:"image/png",buffer:tinyPng});
 await page.locator("#garmentPreview").waitFor({state:"visible"});
 await page.locator("#garmentForm button[type=submit]").click();
 await page.getByText("Prenda auditada").waitFor();
 await page.reload({waitUntil:"networkidle"});
 await page.getByText("Prenda auditada").waitFor();
 await page.locator('[data-view="stylist"]').click(); await page.locator('#openLooks').click();
 await page.locator("#newLook").click();
 await page.locator("#lookName").fill("Look auditado");
 await page.locator('#lookGarments input[type="checkbox"]').first().check();
 await page.locator("#lookForm button[type=submit]").click();
 await page.getByText("Look auditado").waitFor();
 await page.locator('[data-view="wardrobe"]').click();
 await page.locator("#addGarment").click();
 await page.locator("#autoAnalyze").check();

 await page.locator("#garmentImage").setInputFiles({name:"foto.png",mimeType:"image/png",buffer:tinyPng});
 await page.getByText("Análisis completado").waitFor();
 assert.equal(await page.locator("#meta-fabric").inputValue(),"cotton");
 assert.equal(await page.locator("#meta-fit").inputValue(),"regular");
 assert.equal(await page.locator("#meta-sleeve").inputValue(),"larga");
 assert.equal(await page.locator("#meta-subtype").inputValue(),"camisa");
 await page.locator("#meta-brand").fill("Marca introducida a mano");
 assert.equal(await page.locator("#garmentName").inputValue(),"Camisa reconocida por IA");
 assert.equal(await page.locator("#garmentCategory").inputValue(),"Arriba");
 await page.locator("#garmentForm button[type=submit]").click();
 await page.getByText("Camisa reconocida por IA").first().waitFor();
 await page.reload({waitUntil:"networkidle"});
 await page.locator('[data-garment]').filter({hasText:"Camisa reconocida por IA"}).first().click();
 assert.equal(await page.locator("#meta-fit").inputValue(),"regular");
 assert.equal(await page.locator("#meta-brand").inputValue(),"Marca introducida a mano");
 await page.locator("#closeGarment").click();
 await page.locator('[data-view="stylist"]').click(); await page.locator('#openLooks').click();
 await page.locator("#aiLooks").click();
 await page.getByText("Look de prueba IA").waitFor();
 await page.locator('[data-view="wardrobe"]').click();
 await page.locator('[data-fav]').first().click();
 await page.locator('[data-wear]').first().click();
 await page.locator("#wearSheet [data-wear-day]").first().click();
 await page.locator("#toast",{hasText:"Uso registrado"}).waitFor();
 await page.locator('[data-view="shopping"]').click();
 await page.locator('[data-shop-tab="wish"]').click();
 await page.locator('[name="wishName"]').fill("Abrigo de prueba");
 await page.locator('[name="wishPrice"]').fill("80");
 await page.locator('#wishlistForm button[type="submit"]').click();
 await page.getByText("Abrigo de prueba").waitFor();
 await page.locator('[data-view="insights"]').click();
 await page.getByRole("heading",{name:"Prendas olvidadas"}).waitFor();
 await page.locator("#goCalendar").click();
 await page.getByRole("heading",{name:"Calendario de looks"}).waitFor();
 assert.ok(await page.locator("[data-remove-use]").count()>0,"Wear records must appear in calendar");
 await page.locator('[data-view="stylist"]').click();
 await page.locator("#prefDiversity").evaluate(el=>{el.value="80";el.dispatchEvent(new Event("input",{bubbles:true}))});
 await page.locator("#openLooks").click();
 const existingLooks=await page.locator("[data-look]").count();
 forceServerError=true;
 await page.locator("#aiLooks").click();
 await page.getByText("No se pudieron generar looks").waitFor();
 assert.equal(await page.locator("[data-look]").count(),existingLooks,"Server failures must not create looks");
 await page.locator('[data-view="stylist"]').click();
 await page.locator("#prefDiversity").evaluate(el=>{el.value="90";el.dispatchEvent(new Event("input",{bubbles:true}))});
 await page.locator("#openLooks").click();
 forceUnauthorized=true;
 await page.locator("#aiLooks").click();
 await page.locator("#auth").waitFor({state:"visible"});
 assert.equal(await page.locator("#app").isVisible(),false);
 assert.equal(await page.getByText("Prenda auditada").count(),0,"Logout must purge private DOM");
 assert.equal(await page.locator("#lookGarments").textContent(),"","Private look picker must be cleared");
 currentProfile="irene";
 await page.getByRole("button",{name:"Irene"}).click();
 await page.locator("#password").fill("test");
 await page.locator("#loginBtn").click();
 await page.getByRole("heading",{name:"Mi armario"}).waitFor();
 assert.equal(await page.getByText("Prenda auditada").count(),0,"Profile isolation broken");
 assert.equal(await page.getByText("No hay prendas con estos filtros").count(),1);
 assert.deepEqual(errors,[]);
 await page.screenshot({path:"atelier-smoke.png",fullPage:true});
 console.log("PASS: iPhone viewport, styles, login, wardrobe CRUD, IndexedDB persistence, manual looks, AI garment recognition, AI looks, AI outages, expired sessions, profile isolation");
}finally{await browser.close()}
