import fs from "node:fs";
const html=fs.readFileSync(new URL("./index.html",import.meta.url),"utf8");
const js=fs.readFileSync(new URL("./app-v2.js",import.meta.url),"utf8");
const css=fs.readFileSync(new URL("./styles-v2.css",import.meta.url),"utf8");
const sw=fs.readFileSync(new URL("./sw.js",import.meta.url),"utf8");
const features=fs.readFileSync(new URL("./features-v3.js",import.meta.url),"utf8");
const features4=fs.readFileSync(new URL("./features-v4.js",import.meta.url),"utf8");
const css4=fs.readFileSync(new URL("./styles-v4.css",import.meta.url),"utf8");
const mustHtml=["styles-v2.css","styles-v4.css","app-v2.js","features-v3.js","features-v4.js","https://api.open-meteo.com",'data-view="stylist"','data-view="shopping"','data-view="insights"','id="garmentPreview"','id="auth"','id="app"','id="garmentForm"','id="lookForm"'];
const mustJs=["/api/login","/api/analyze","/api/looks","indexedDB.open","state:",'localStorage.setItem("atelier-session"',"lastAnalysis","liked:taste"];
// Funciones de features-v4.js que no deben desaparecer al reescribir archivos
const mustV4=["saveState=async function","loadState=async function","imgKey","lookCard=function","evaluateCandidate","shoppingSuggestions","looksAround","fetchTodayTemperature","AI_LIMITS","DEFAULT_TEMPERATURE=25","toLong","promptWear=function"];
const forbidden=["document.write(","document.open(","__ATELIER_B64","payload.js","fflate"];
for(const x of mustHtml)if(!html.includes(x))throw new Error("HTML missing: "+x);
for(const x of mustJs)if(!js.includes(x))throw new Error("JS missing: "+x);
for(const x of forbidden)if(html.includes(x)||js.includes(x))throw new Error("Forbidden legacy runtime: "+x);
for(const x of mustV4)if(!features4.includes(x))throw new Error("features-v4.js missing: "+x);
if(js.includes("sessionStorage.setItem"))throw new Error("La sesión debe guardarse en localStorage, no en sessionStorage");
if(html.indexOf("features-v3.js")>html.indexOf("features-v4.js"))throw new Error("features-v4.js debe cargarse después de features-v3.js");
if(css.length<3000)throw new Error("CSS unexpectedly small");
if(css4.length<1500)throw new Error("styles-v4.css unexpectedly small");
new Function(features4);
new Function(js);
new Function(features);
new Function(sw);
for(const asset of ["./styles-v2.css","./styles-v4.css","./app-v2.js","./features-v3.js","./features-v4.js","./manifest.json"])if(!sw.includes(asset))throw new Error("SW missing asset: "+asset);
console.log("Atelier release gate OK (v3 + v4)");